// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHqlR3x-sVsTpdJHpfoSeWUcoZ0XVrcnc',
    appId: '1:596706096553:web:bad385b9793ad1326900b8',
    messagingSenderId: '596706096553',
    projectId: 'crud-99f1e',
    authDomain: 'crud-99f1e.firebaseapp.com',
    storageBucket: 'crud-99f1e.firebasestorage.app',
    measurementId: 'G-ZKHQ01RGRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqIXRjYg1jyn8BkbpKnzTnoK2nHPA9dzE',
    appId: '1:596706096553:android:4df224ee168ee2cc6900b8',
    messagingSenderId: '596706096553',
    projectId: 'crud-99f1e',
    storageBucket: 'crud-99f1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBBA5Cw7NgZ9fWyMhZ1_LIFs_k8xEHNbE',
    appId: '1:596706096553:ios:40503b95fef703de6900b8',
    messagingSenderId: '596706096553',
    projectId: 'crud-99f1e',
    storageBucket: 'crud-99f1e.firebasestorage.app',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBBA5Cw7NgZ9fWyMhZ1_LIFs_k8xEHNbE',
    appId: '1:596706096553:ios:40503b95fef703de6900b8',
    messagingSenderId: '596706096553',
    projectId: 'crud-99f1e',
    storageBucket: 'crud-99f1e.firebasestorage.app',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHqlR3x-sVsTpdJHpfoSeWUcoZ0XVrcnc',
    appId: '1:596706096553:web:d07cf5d043e48e2d6900b8',
    messagingSenderId: '596706096553',
    projectId: 'crud-99f1e',
    authDomain: 'crud-99f1e.firebaseapp.com',
    storageBucket: 'crud-99f1e.firebasestorage.app',
    measurementId: 'G-Y0CZFCPSFW',
  );

}